### ISSUE TITLE
Avoid ts_key entry in the unlocalized_meta_data JSON

### ISSUE THREAD

**Issue by omuelle** [mbannert/timeseriesdb#104]
Since readMetaInformation cannot handle it, it would be best to not allow writing it with storeMetaInformation.

**Comment by HomoCodens** [comment]
Same for localized meta.

Disallowing the writing of such a field in tsdb functions is one part but I think we should also put some measures in place in `readMetaInformation` in case the column gets written via some other means.

Renaming the column or something maybe.
