### ISSUE TITLE
Avoid adding unlocalized_ prefix to unlocalized meta data identifiers in readMetaInformation

### ISSUE THREAD

**Issue by omuelle** [mbannert/timeseriesdb#106]
When for example alias or legacy_key is being stored, readMetaInformation returns unlocalized_alias or unlocalized_legacy_key. This is a bit confusing. If we could enforce uniqueness of meta_data identifiers across localized/unlocalized, that would be ideal. Not high priority though.

**Comment by HomoCodens** [comment]
this won't be an issue anymore in v1
