### ISSUE TITLE
delete, update timeseries

### ISSUE THREAD

**Issue by mbannert** [mbannert/timeseriesdb#113]
admins can delete 

- [] time series (incl. history)
- [] last vintage
- [] entire datasets

- safe guard makes this function only available for interactive use.

**Comment by HomoCodens** [comment]
* Updating: That should really only be possible at the edge. Either automatically when storing a second time or delete and re-store.
* Deleting:
  * Deleting a whole time series should be possible but only by admins
  * Deleting the current edge... I tend towards not letting writer users do that but make it easy to update the current edge.

**Comment by HomoCodens** [comment]
I was thinking something like ` ON CONFLICT (ts_key, validity) UPDATE;`
But then that requires writers to have update privileges which in turn needs a trigger to prevent updates of past vintages. Then again maybe such a trigger makes sense anyway to protect admins from themselves...

**Comment by HomoCodens** [comment]
To be super duper  proper we could of course keep the overwritten vintage(s) and just mark them as such.
