### ISSUE TITLE
design migration project

### ISSUE THREAD

**Issue by mbannert** [mbannert/timeseriesdb#117]

**Comment by HomoCodens** [comment]
Building JSON ts data from the old HSTORE is actually quite easy.
This migration can be done entirely on the database I think.

**Comment by HomoCodens** [comment]
9eb49de00dddbb60dd8dd5f150ec3246f9d80de4

**Comment by mbannert** [comment]
- [x]    data migration, e.g., KOFCASTS (needed were data/vintages can't be reproduced)
- [x] backup current schemas: timeseries, pblc_timseries, restricted
- [x] enter datasets to time series ts-registry
- [x] run aggregation locally with dev branch of kofbts package
