### ISSUE TITLE
check whether LOCK TABLES TO EXCLUSIVE MODE is still a good idea

### ISSUE THREAD

**Issue by mbannert** [mbannert/timeseriesdb#119]
see also: 
https://github.com/mbannert/timeseriesdb/blob/master/R/sqlQueries.R

**Comment by HomoCodens** [comment]
What was the original reason for this?

`Also, most PostgreSQL commands automatically acquire locks of appropriate modes to ensure that referenced tables are not dropped or modified in incompatible ways while the command executes.`
https://www.postgresql.org/docs/11/explicit-locking.html

**Comment by HomoCodens** [comment]
Also this maybe
https://www.cybertec-postgresql.com/en/lock-table-can-harm-your-database/

**Comment by mbannert** [comment]
Not really relevant in our functions approach anymore. Can't access the DB w/o the functions anymore. Reopen if the problem shows up again, but I guess we're covered here.
