### ISSUE TITLE
Failed to fetch row: ERROR:  role "timeseries_admin" does not exist

### ISSUE THREAD

**Issue by HomoCodens** [mbannert/timeseriesdb#147]
Catch it, throw something along the lines of "wrong schema"

Alternatively just check for existence of schema in all db_functions...?

**Comment by HomoCodens** [comment]
actually, this particular one can be neatly handled in the new `db_grant_to_admin`

What other errors could occur when using a nonexistent schema?

**Comment by mbannert** [comment]
just handle this in `db_grant....` function because the error message is not obvious, I am rooting for the experienced users to figure out the other case for now.
