### ISSUE TITLE
get smart on timestamptz

### ISSUE THREAD

**Issue by HomoCodens** [mbannert/timeseriesdb#155]
1) How is it stored (in UTC + offset)
2) How does it interact with R and the local timezone? Do the readers/writers accurately transfer the offset?

There is something funny going on with a test for the release calendar but I'm postponing the investigation for now.

**Comment by mbannert** [comment]
Started a discussion here: https://github.com/r-dbi/RPostgres/issues/250

**Comment by HomoCodens** [comment]
outdated packages are outdated...
