### ISSUE TITLE
deleteSeries function does not work

### ISSUE THREAD

**Issue by mbannert** [mbannert/timeseriesdb#17]
deleteTimeSeries(series = "ro.ds.oecdeo.gfcf",con = con, schema = "xxxx")
 
 
Error in postgresqlExecStatement(conn, statement, ...) :
  RS-DBI driver: (could not Retrieve the result : ERROR:  syntax error at or near "CASCADE"
LINE 1: ...OM timeseries_main WHERE ts_key ='ro.ds.oecdeo.gfcf' CASCADE
                                                                ^
)
Warning in postgresqlQuickSQL(conn, statement, ...) :
  Could not create executeDELETE FROM timeseries_main WHERE ts_key ='ro.ds.oecdeo.gfcf' CASCADE
 
[1] "Time series ro.ds.oecdeo.gfcf deleted."

**Comment by mbannert** [comment]
@HomoCodens  can you check whether this is still true?

**Comment by HomoCodens** [comment]
There is no PSQL error anymore, but the delete still seems to not work:

```
dbGetQuery(con_test, "SELECT ts_key from pblc_timeseries.timeseries_main limit 10")
         ts_key
1  baro_2014m04
2  baro_2014m05
3  baro_2014m06
4  baro_2014m07
5  baro_2014m08
6  baro_2014m09
7  baro_2014m10
8  baro_2014m11
9  baro_2014m12
10 baro_2015m01
> deleteTimeSeries("baro_2014_m04", con_test, schema = "pblc_timeseries")
DELETE operations in 1 chunk(s) performed.
> dbGetQuery(con_test, "SELECT ts_key from pblc_timeseries.timeseries_main limit 10")
         ts_key
1  baro_2014m04
2  baro_2014m05
3  baro_2014m06
4  baro_2014m07
5  baro_2014m08
6  baro_2014m09
7  baro_2014m10
8  baro_2014m11
9  baro_2014m12
10 baro_2015m01
```

Could of course just be a rights issue on my part.
If so we should add a warning for insufficient rights.

**Comment by HomoCodens** [comment]
Oops, there was an underscore too many in the key...
Looks like it's working:
```
> dbGetQuery(con_test, "SELECT ts_key from pblc_timeseries.timeseries_main limit 10")
         ts_key
1  baro_2014m06
2  baro_2014m07
3  baro_2014m08
4  baro_2014m09
5  baro_2014m10
6  baro_2014m11
7  baro_2014m12
8  baro_2015m01
9  baro_2015m02
10 baro_2015m03
> deleteTimeSeries("baro_2014m06", con_test, schema = "pblc_timeseries")
> dbGetQuery(con_test, "SELECT ts_key from pblc_timeseries.timeseries_main limit 10")
         ts_key
1  baro_2014m07
2  baro_2014m08
3  baro_2014m09
4  baro_2014m10
5  baro_2014m11
6  baro_2014m12
7  baro_2015m01
8  baro_2015m02
9  baro_2015m03
10 baro_2015m04
```
