### ISSUE TITLE
unit tests

### ISSUE THREAD

**Issue by mbannert** [mbannert/timeseriesdb#23]
- read m,q,d,semi-annual
- store m,q,d,semi-annual
- read / write meta unlocal
- read / write meta local

**Comment by HomoCodens** [comment]
Are those the tests in `test_CRUD.R` or do we need additional ones?
Probably one or two for the new release date wouldn't hurt.

**Comment by mbannert** [comment]
Yup, let's do release date and vintages and we're done here for the release.
Cool, you found `skip_on_cran`. How about the initial paragraphs where the connection is made. Don't we need something there too?

**Comment by HomoCodens** [comment]
Hm, yes the `createConObj` and `dbDisconnect` functions also throw errors if no suitable db is present.
Wrapped them in a `skip_on_cran`-like block.

**Comment by mbannert** [comment]
basic units tests available, closed for now. Raise new ideas as single issues.
