### ISSUE TITLE
which functions can be removed?

### ISSUE THREAD

**Issue by mbannert** [mbannert/timeseriesdb#27]

**Comment by HomoCodens** [comment]
**Duplicates from tstools:**
* `importTsList.R` Reads csv to ts list
* `plotMethod.R` Caveman's tsplot
* `%k%`: The operation is not really suited for a binary operator. Depends on an env variable.
* `resolveOverlap.R`

**Related to DB-Explorer:**
* `dbExplorerUtils.R`
* `exploreDB.R`

**Misc:**
* `writeLogFile.R`?

**Comment by mbannert** [comment]
- imports ... can be removed without further ado
- plot ... can be removed without further ado
- %k% let's discuss this, I am not sure yet, but tend to get rid of it, too.
- resolveOverlap, maybe should be deprecated, maybe just removed.
- dbexplorer, simply remove it

- writeLogFile: very helpful, used often in our production. definitely keep it.

**Comment by HomoCodens** [comment]
The problem with `%k%` is that it needs not only the key-regex to look for (`conn %k% "ch.kof.*"`) but also the schema in which to look.
Currently it gets the schema via an environment variable which seems a bit hacky. At the very least there should be a sensible default (`"timeseries"`) if `TIMESERIESDB_SCHEMA` can't be found.

Or maybe provide a "constructor" along the lines of `createMetaDataHandle`.

```
"%k%" <- function(conObj,regexp){
  schema <- Sys.getenv("TIMESERIESDB_SCHEMA")
  # get time series keys that suit the regexp
  sql_query <- sprintf("SELECT ts_key FROM %s.timeseries_main WHERE ts_key ~ '%s'",
                       schema,regexp)
  keys <- dbGetQuery(conObj,sql_query)$ts_key
  
  ts_list <- readTimeSeries(keys,conObj)
  return(ts_list)
}
```

**Comment by mbannert** [comment]
hmm, I don't know. Do you like this operator at all? Do you feel this could be useful? 
I am not so sure anymore... Maybe we can park it somewhere? Like put it on another branch to not loose the idea entirely.

**Comment by HomoCodens** [comment]
I must admit when I first saw it the idea of a binary operator between an SQL connection and a string struck me as very odd. Especially since it does not just check for the existence of keys or get them but gets the whole time series.

It's neat but I feel a `readTimeSeriesMatching` or even just a regex option for the existing `readTimeSeries` would do just as well.

**Comment by mbannert** [comment]
agreed. let's get rid of it and move forward. We need to be careful with that regexp option and test it thoroughly because we have a lot of dependencies, but it seems like the best long term option. Maybe we could have something like exact = T which is a default in order not to break old code. 

In SQL, the `~` operator is quite slow compared to `=` which is why we should stick to `=` as the default.

**Comment by HomoCodens** [comment]
Closing as Code cleanup is merged.

**Comment by HomoCodens** [comment]
What about `bulkStoreTimeSeries`?
This appears very similar to `storeTimeSeries`. An earlier version/prototype?

**Comment by mbannert** [comment]
No, bulkStore is actually a speed up experiment to speed up store time series. I removed it for now and parked it on another branch. I am not sure how much of it was implemented in storeTimeSeries. Yet, it is not used in production. I think deleting it for now is good (which I did on most recent dev).

**Comment by HomoCodens** [comment]
OK
#36 also has to do with speeding up `storeTimeSeries`, check it out if you have the time.

**Comment by mbannert** [comment]
Hmm, you're right about #36. I think we should re-group. We could make use of the latest add-ons and some of the more obvious clean-ups soon while optimizing like this takes some more time. 

I suggest we introduce another mile stone called release-date-feature and put

- all release date feature relevant stuff  (incl. update create table statements)
- all checks, warnings errors and current unit test (so it feels more stable)

in there. Fix that first and then look at CRAN release. Let's re-organize after lunch :)
