### ISSUE TITLE
CHECK pass notes

### ISSUE THREAD

**Issue by mbannert** [mbannert/timeseriesdb#31]
rhub r-devel

**Comment by HomoCodens** [comment]
```
N  checking for hidden files and directories
   Found the following hidden files and directories:
     .travis.yml
   These were most likely included in error. See section ‘Package
   structure’ in the ‘Writing R Extensions’ manual.
```

**Comment by HomoCodens** [comment]
Is this a problem? Complaining about a file that triggers the check in the first place (with Travis) seems a bit circular.

Do we even use Travis atm?

**Comment by mbannert** [comment]
other build environments than the super basic R (and pedantic devel) have buildingore files which is why travis works on travis. But we don't officially use it right now. I just tested it. I like it but timeseriesdb might not be the best package to work with travis for starters because of its PG dependency. I think we can get rid of the file for now.
