### ISSUE TITLE
vintages table release date problem

### ISSUE THREAD

**Issue by mbannert** [mbannert/timeseriesdb#40]
Can't store to vintages tables because of a bug that has likely to do with the newly introduced release date. Number of columns for an INSERT does not correspond with the number of VALUES. I guess this about temp tables etc.

**Comment by HomoCodens** [comment]
Vintages completely flew by me... :bow:

**Comment by mbannert** [comment]
Hmm, I am not so sure whether I agree with what you said when you stated that vintages don't have release dates. Admittedly, release dates are used much less often, but what about the current vintage? 
That might a release date. The idea is not to use the standard table and the vintage table, but use the vintage table all the time for series that should keep vintages. 

But as I said, I am not sure either. Maybe the best solution is to use the validity as some kind of release date as well, so there be extra endpoints for vintage table series.
