### ISSUE TITLE
Progress indicator for storeListChunkWise

### ISSUE THREAD

**Issue by HomoCodens** [mbannert/timeseriesdb#49]
When manually storing large lists, some indication that work is being done and how far along the process is would be neat.

Maybe add a `verbose` or `show_progress` parameter that defaults to `FALSE`.

**Comment by mbannert** [comment]
Good idea. Would love to have that. How can we implement this? Guess an easy way would be to do it using the number of chunks we loop over. Not super precise but does the job. Would also be nice to have that for the non-chunkwise version, but I guess this would be more difficult to do. 

bottom line: I think an easy solution would be nice but we should not over-engineer for the upcoming facelift release. Chances are there will be very substantial changes to the backend once we involve external collaborators as planned.

**Comment by HomoCodens** [comment]
Yes, I was thinking of something trivial like
```
Now working on chunk i/n_chunks...
```

Maybe a simple, text based, progress bar at the fanciest.

Like so:
```R
n <- 1234
chunk_size <- 100

console_width <- getOption("width")
bar_width <- console_width - 5

for(i in seq(1, n + chunk_size, chunk_size)) {
  i <- min(i, n)
  progress <- (i/n)
  cat(sprintf("\r|%s%s| %d%%",
              paste(rep("=", floor(bar_width * progress)), collapse = ""),
              paste(rep(" ", ceiling(bar_width * max(0, (1 - progress)))), collapse = ""),
              floor(100*progress)))
  Sys.sleep(0.5)
}
```
