### ISSUE TITLE
Issues with release dates and vintages

### ISSUE THREAD

**Issue by HomoCodens** [mbannert/timeseriesdb#53]
`timeseries.timeseries_vintages` does not currently have a release date column.

@omuelle
Could you provide a code example of what fails with the newer version?

**Comment by omuelle** [comment]
I have my own vintages table with a column ts_release_date, but it shouldn't be used for testing. The query returned by `timeseriesdb::createTimeseriesVintages` doesn't actually create such a column. I added it at some point.

**Comment by HomoCodens** [comment]
So what exactly is the issue then?

You can't very well expect `timeseriesdb` to work with a table it wasn't designed for.

**Comment by omuelle** [comment]
@mbannert 

Are there any short to medium term plans to use the release date for vintages? For example to get away from the `baro_2018m06` type keys we currently use for the baro vintages in `pblc_timeseries`? I do not need the release date for the baro computation, so I'm fine with removing the ts_release_date columns.

**Comment by mbannert** [comment]
Yes, baro keys and vintages etc. are in the midterm plan, not the short run (next CRAN release) though.

**Comment by mbannert** [comment]
closed for now.
