### ISSUE TITLE
ERROR:  data type text has no default operator class for access method "gist"

### ISSUE THREAD

**Issue by sboriss** [mbannert/timeseriesdb#62]
Running the following command to set up the table with vintages reports the following

runDbQuery(con, createTimeseriesVintages(schema = "timeseries", tbl = "timeseries_vintages") )
Error in postgresqlExecStatement(conn, statement, ...) : 
  RS-DBI driver: (could not Retrieve the result : ERROR:  data type text has no default operator class for access method "gist"
HINT:  You must specify an operator class for the index or define a default operator class for the data type.
)
WARNING:  there is no transaction in progress
data frame with 0 columns and 0 rows

All the rest of commands (createTimeseriesMain, createTimeseriesSets, etc.) were executed without any problem.

**Comment by mbannert** [comment]
Looks like the `btree_gist` extension is missing. See the vignette for more details: 

https://github.com/mbannert/timeseriesdb/blob/cran_releases/vignettes/timeseriesdb.Rmd

run 

```
vignette("timeseriesdb")
```

should be a matter of running 

```
CREATE EXTENSION btree_gist;
```

in your postgres console.

**Comment by sboriss** [comment]
Indeed, it was missing. Now it works.
