### ISSUE TITLE
updateMetaInformation returns an ERROR

### ISSUE THREAD

**Issue by sboriss** [mbannert/timeseriesdb#63]
> tsl <- list(
+       ts1 = ts(rnorm(100),start = c(1990,1),freq = 4),
+       ts2 = ts(rnorm(100),start = c(1985,1),freq = 12),
+       ts3 = ts(rnorm(50),start = c(2000,1),freq = 4))
> storeTimeSeries(names(tsl), con, tsl)
$data.names
character(0)

$data.row.names
integer(0)

$data.class
[1] "data.frame"

$data.query_status
[1] "OK"

$meta_data.names
character(0)

$meta_data.row.names
integer(0)

$meta_data.class
[1] "data.frame"

$meta_data.query_status
[1] "OK"

> read_it <- readTimeSeries(c("ts1","ts2"),con)
> m_e <- new.env()
> m_en <- list("wording" = "let's have a word.",
+                "check" = "it's english man.!! SELECTION DELETE123")
> addMetaInformation("ts1",m_en,m_e)
x contains 1 meta information object(s).
> # DE
>   m_d <- new.env()
> m_de <- list("wording" = "Wir müssen uns mal unterhalten......",
+                "check" = "Das ist deutsch. wirklich")
> addMetaInformation("ts1",m_de,m_d)
x contains 1 meta information object(s).
> updateMetaInformation(m_e,
+                       con,
+                       locale = "en",
+                       tbl = "meta_data_localized")
Error in `$<-.data.frame`(`*tmp*`, "locale", value = "en") : 
  replacement has 1 row, data has 0
> updateMetaInformation(m_d,
+               con,
+               locale = "de",
+               tbl = "meta_data_localized")
Error in `$<-.data.frame`(`*tmp*`, "locale", value = "de") : 
  replacement has 1 row, data has 0

**Comment by mbannert** [comment]
@homocodens can you confirm this? Thought we had fixed this?

**Comment by HomoCodens** [comment]
Yes, it works on the `dev` branch.

The problem is in d47ed0a4 where the `keys` parameter is added to `updateMetaInformation.data.frame` (as it should be to pass CRAN compliance checks for generics) but the call in `updateMetaInformation.meta_env` uses positional arguments so it all falls apart/keys has the value of `quiet` which is `FALSE`.

Easy to fix though.

**Comment by mbannert** [comment]
@sboriss we just pushed an update to CRAN that should fix this issue which was related to most recent change. 0.4.1 is what you're looking for.  Thanks for reporting!
