### ISSUE TITLE
storeTsList call doesn't find class-specific methods

### ISSUE THREAD

**Issue by omuelle** [mbannert/timeseriesdb#67]
When set_keys is of class character:

> Error in UseMethod("storeTsSet", set_keys) : 
  no applicable method for 'storeTsSet' applied to an object of class "character"

When set_keys is of class list:

> Error in UseMethod("storeTsSet", set_keys) : 
  no applicable method for 'storeTsSet' applied to an object of class "list"

**Comment by mbannert** [comment]
are we using this function only recently? I can't remember any recent changes to this function. 
What's the context in which the error appears all of a sudden?

**Comment by omuelle** [comment]
I used it to create the set of baro vintages, as I do every month. I think I haven't used it otherwise for creating sets in the past month or so.
