### ISSUE TITLE
Rethink ts sets

### ISSUE THREAD

**Issue by HomoCodens** [mbannert/timeseriesdb#84]
Ts sets are currently stored as hstores of the form key => key_type.
Since (as far as I can tell) the only key_type ever used is ts_key, we could rethink this and maybe store them as arrays for example.

**Comment by mbannert** [comment]
I see you point. And I agree we should simply use an array here. However, not a huge problem right now. Let's move on, but at least make *ts_key* dynamic.

**Comment by mbannert** [comment]
Hmm. tsSets keep frustrating me. Somehow method dispatch still doesn't work. Guess we need to fix it before closing this issues @HomoCodens

**Comment by HomoCodens** [comment]
Yes, I noticed that too.
I removed the @export for storeTsSet.character at some point, thinking it was not necessary (seems to work like that for other packages?) but apparently that broke it again.

**Comment by mbannert** [comment]
Guys, I'd love to slap my former self for implementing it the way I did. I have no idea why I thought it would be clever to it that way. Let's get rid of this crappy handling of sets and make it simpler. IMMEDIATELY with the next release. I am going crazy over this. 🦀 💣 🐗 🔩 

Unless you use your veto power (which you certainly have) .. let's go!

**Comment by HomoCodens** [comment]
My two cents:

1) The most pressing issue is with the R interface which does not properly dispatch the .character method
2) Overall, from a conceptual standpoint, changing the database implementation of the sets makes absolute sense too but it's not super urgent as long as the interface works
3) The sooner we change it though the smaller the impact / migration effort when we **do**

So yes, if we can fit it in absolutely.

**Comment by omuelle** [comment]
Definitely ok with this.
