### ISSUE TITLE
Reading localized meta data fails when there are none

### ISSUE THREAD

**Issue by omuelle** [mbannert/timeseriesdb#86]
IMO that shouldn't happen, since by default only unlocalized meta data is written. Instead I suggest returning an empty table or one with only a ts_key column, and a warning. I have to do a try catch otherwise.

> readMetaInformation(cons$test, std_keys, locale = "de", as_list = F)
Error in readMetaInformation(cons$test, std_keys, locale = "de", as_list = F) : 
  None of the provided series were found in timeseries.meta_data_localized

**Comment by omuelle** [comment]
In fact I would not even do a warning, just a message.

**Comment by mbannert** [comment]
I agree a message should be enough. Good feedback, thanks!

**Comment by HomoCodens** [comment]
👍 
Error is too much here. I'll make it give a warning if some (or all) series were not found and return an empty tsmeta object in case none were found. This is consistent with the behaviour when only some are missing where it also returns what it can find.

**Comment by omuelle** [comment]
I think a warning might be too much, since it's a normal use case. I think we should be able to run our code with warnings treated as errors.

**Comment by HomoCodens** [comment]
I'm not so sure about this being the normal use case.
I picture a user who usually knows pretty well what series they want to read and whether there's metadata for them.

Also when trying to read some manually/interactively a warning can be a good hint at typos.

What happens if you treat warnings as errors and wrap code about whose warnings you don't care in `suppressWarnings`? Would that work?

**Comment by omuelle** [comment]
Warnings are usually reserved for stuff that is potentially "code-breaking", like using a deprecated function. They should never be suppressed, but be fixed. But I admit that's the developer perspective. Users might prefer a warning to a simple message, since for them something has failed. It's fine with me.

**Comment by HomoCodens** [comment]
All in all, wouldn't it make sense to be rid of the localized/unlocalized destinction when reading?
Just have `readMetaInformation` return the few bits of unlocalized meta plus whatever localized there is.

Opinions?

**Comment by omuelle** [comment]
I would like that, or maybe a flag to add unlocalized in addition to localized. Right now you have to pass the table name and set locale to NULL, which seems a bit excessive.

**Comment by mbannert** [comment]
Great discussion guys. I like the ideas that came up in this. To me we should 

- have a single pair of read/store functions for meta data. 
- get rid of the table switching / locale to NULL thing. 
- still be flexible w.r.t. the table names. Still we would have default table names.
- make sure we do not break the mechanism that stores unlocalized meta information when we add / update series

Also, lemme add my 2 cents to the warning/error discussion. 
I agree with @omuelle that a common case is to have unlocalized meta information only. I admit that we have more and more complete data in the sense that there is localized meta information. 🚀 !
But still there are others who start to use timeseriesdb and might not use localized meta information. 
Hence we need to cover this scenario. I think we should not throw any error / warning / message at all. In fact I would return the same type of object every time you call readMetaInformation, like so:

```
$meta_data_unlocalized
       # some data.frame

$meta_data_localized
      # some data.frame
      # just return a character status message or single column data.frame with
      # in case this is empty.
```

I've done a similar thing with the `dbGetQuery` return in `storeTimeSeries`. It is important to return the same type of object – no matter what the result is. A detail that I am not overly concerned with is whether we return all locales by default, a default locale or require to specify a locale. From user perspective a default locale would have the problem that another locale might be present, but not the default and the user will never now without a message. Maybe just adding a question / hint to the status message when empty would do the trick. 

🏀 .

**Comment by HomoCodens** [comment]
I've added the notion of "empty tsmeta object" in e765c2de142a824f1bf8680f25096d798dc9c5c5 so if no metadata at all is present that can be returned.

I don't think we need the distinction between localized and unlocalized in the return value either. Just return a df with the corresponding columns:

```
created_at coverage_temp last_update [if pesent: localized_a, localizec_b...]
```

That way the user can just
```R
tslist <- ...
x <- readMetaInformation(..., as_list = TRUE)

for(k in names(tslist)) {
  if(length(x[[k]]) > 0) {
    # Metadata is present
  } else {
    # ts does not exist in DB
  }
}
```

No error/warning/message given if ts does not exist.

**Comment by omuelle** [comment]
Will this be merged into json_meta?

**Comment by HomoCodens** [comment]
Yes and no.

I made a new branch "tsdb-11-2018" for all the changes since we're also redoing sets, argument order etc.
