### ISSUE TITLE
Error when reading unlocalized meta data

### ISSUE THREAD

**Issue by omuelle** [mbannert/timeseriesdb#87]
This fails for some reason:

> readMetaInformation(cons$test, std_keys, locale = NULL, tbl = "meta_data_unlocalized", as_list = F)
Error in if (is.character(txt) && length(txt) == 1 && nchar(txt, type = "bytes") <  : 
  missing value where TRUE/FALSE needed

std_keys is here (is there no way to upload RData or csv? Kind of annoying):
[std_keys.xlsx](https://github.com/mbannert/timeseriesdb/files/2580899/std_keys.xlsx)

**Comment by omuelle** [comment]
Sehr gut, probiere ich gleich aus.

**Comment by omuelle** [comment]
Gibt einen anderen Fehler:

```
f4_keys <- sub("\\.fx\\.", ".f4.", std_keys)
readMetaInformation(cons$test, f4_keys, locale = NULL, schema = "kofbts")
Error in postgresqlExecStatement(conn, statement, ...) : 
  RS-DBI driver: (could not Retrieve the result : ERROR:  invalid byte sequence for encoding "UTF8": 0xa2
)
WARNING:  there is no transaction in progress
Error in lapply(meta_data, expand_meta) : object 'meta_data' not found
```

Oder mit locale "de":
```
readMetaInformation(cons$test, f4_keys, locale = "de", schema = "kofbts")
Error in lapply(meta_data, expand_meta) : object 'meta_data' not found
```

**Comment by mbannert** [comment]
Looks like the data.table error we had before. Can you try to `library(data.table)` ? 
Other than that – is the kofbts schema migrated to the new json meta information yet?

**Comment by omuelle** [comment]
I'm sure data.table was loaded. I simply ran the aggregation on RStudio1. As for the kofbts schema, that's a good point. It should be changed too, if nobody has already (?). That said, I also tried it on the timeseries/restricted schema with std_keys.

**Comment by omuelle** [comment]
Like this:

```
md <- readMetaInformation(cons$test, std_keys, locale = "de")
Error in lapply(meta_data, expand_meta) : object 'meta_data' not found
md <- readMetaInformation(cons$test, std_keys, locale = NULL)
Error in postgresqlExecStatement(conn, statement, ...) : 
  RS-DBI driver: (could not Retrieve the result : ERROR:  invalid byte sequence for encoding "UTF8": 0xc1 0x01
)
WARNING:  there is no transaction in progress
Error in lapply(meta_data, expand_meta) : object 'meta_data' not found
```

**Comment by mbannert** [comment]
Ok, then. On test the metadata schemas are migrated to json, but not on prod. 
Are we sure it's on the right branch @HomoCodens ? Check code on rstudio1. Should've been deployed there, but maybe it's not.

**Comment by omuelle** [comment]
I know get the following error:

```
md <- readMetaInformation(con, std_keys, locale = NULL)
Error in postgresqlExecStatement(conn, statement, ...) : 
  RS-DBI driver: (could not Retrieve the result : ERROR:  invalid byte sequence for encoding "UTF8": 0xf0 0x1e 0x58 0x02
)
WARNING:  there is no transaction in progress
```

**Comment by omuelle** [comment]
Documentation needs updating that locale = NULL doesn't work anymore, otherwise fine with me.
